### ISSUE TITLE
It seems like the lockfile is not created upon rebuilds.

### ISSUE THREAD

**Issue by rwz** [rondale-sc/ember-cli-rails-addon#10]
When you run `ember build` in a `--watch` mode and change file, it seems that build hooks are not being executed that results the whole lockfile feature not to work. It works fine on initial build though.

Could we investigate? @rondale-sc @rwjblue

**Comment by rondale-sc** [comment]
@rwz Could you give me the steps to replicate.  I just confirmed that ember-cli's build-watch is firing the hooks correctly.  Then checked to ensure that ember-cli-rails-addon's lockfile was being created on each fire of the hook  and found that it was.

**Comment by rondale-sc** [comment]
- ember-cli: 0.1.12
- ember-cli-rails: 0.1.4
- ember-cli-rails-addon: 0.0.11
- node: 0.10.35
- npm: 2.1.8

**Comment by rondale-sc** [comment]
Closing for now (as we discussed @rwz)
