### ISSUE TITLE
Release 0.0.12

### ISSUE THREAD

**Issue by MichaelVdheeren** [rondale-sc/ember-cli-rails-addon#14]
Could you guys release 0.0.12 with the fingerprint issue solved? thx.

**Comment by rondale-sc** [comment]
@MichaelVdheeren Done!  :)

**Comment by MichaelVdheeren** [comment]
Thx, but a tag is missing ;-)

**Comment by rondale-sc** [comment]
@MichaelVdheeren Right on, didn't `git push origin --tags` my bad.  :)  Should be there now.  Sorry it took so long for this release.

**Comment by MichaelVdheeren** [comment]
No problem :-)
