### ISSUE TITLE
DEPRECATION: Overriding init without calling this._super is deprecated.

### ISSUE THREAD

**Issue by aafaq-hassan-confiz** [rondale-sc/ember-cli-rails-addon#33]
New deprecation for ember-cli, seen in ember cli version 2.6.2

**Comment by olivierobert** [comment]
@seanpdoyle We definitely need this

**Comment by williamweckl** [comment]
+1

**Comment by rwjblue** [comment]
Was fixed by #32, but needs a release by either @rondale-sc or @seanpdoyle.

**Comment by aafaq-hassan-confiz** [comment]
Pull request was merged in master branch but latest code has not been pushed to npm

**Comment by rwjblue** [comment]
Yep, that's what I said. :wink:

**Comment by seanpdoyle** [comment]
Released in [0.7.1](https://github.com/rondale-sc/ember-cli-rails-addon/releases/tag/0.7.1).

Thanks for your patience!

**Comment by williamweckl** [comment]
Thank you @seanpdoyle !!! :)
